# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: sodalite
name: k8s
version: 1.0.0
readme: README.md
authors:
  - Mihael Trajbarič (github.com/mihaTrajbaric)
dependencies:
  kubernetes.core: ">=2.0.0"
description: null
license_file: LICENSE
tags:
# tags so people can search for collections https://galaxy.ansible.com/search
# tags are all lower-case, no spaces, no dashes.
  - kubernetes
  - k8s
repository: https://github.com/mihaTrajbaric/k8s
documentation: https://github.com/mihaTrajbaric/k8s/tree/main/docs
homepage: https://github.com/mihaTrajbaric/k8s
issues: https://github.com/mihaTrajbaric/k8s/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
